apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: hello-app
spec:
  type: LoadBalancer
  selector:
    app: hello-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000